### ISSUE TITLE
Unhandled Exception in Sharphound

### ISSUE THREAD

**Issue by variableresults** [BloodHoundAD/BloodHound#148]
Getting this when scanning our forest in default mode:

```
Unhandled Exception: System.AggregateException: AggregateException_ctor_DefaultMessage ---> System.AggregateException: A
ggregateException_ctor_DefaultMessage ---> System.ArgumentException: SIDs with revision other than '1' are not supported
.
Parameter name: binaryForm
   at System.Security.Principal.Win32.ConvertIntPtrSidToByteArraySid(IntPtr binaryForm)
   at System.Security.Principal.SecurityIdentifier..ctor(IntPtr binaryForm)
   at Sharphound2.Enumeration.LocalAdminHelpers.NetLocalGroupGetMembers(ResolvedEntry entry, String& machineSid)
   at Sharphound2.Enumeration.LocalAdminHelpers.<>c__DisplayClass12_0.<GetSamAdmins>b__0()
   at System.Threading.Tasks.Task`1.InvokeFuture(Object futureAsObj)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Sharphound2.Enumeration.LocalAdminHelpers.<GetSamAdmins>d__12.MoveNext()
   at Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass14_0.<StartRunner>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ArgumentException: SIDs with revision other than '1' are not supported.
Parameter name: binaryForm
   at System.Security.Principal.Win32.ConvertIntPtrSidToByteArraySid(IntPtr binaryForm)
   at System.Security.Principal.SecurityIdentifier..ctor(IntPtr binaryForm)
   at Sharphound2.Enumeration.LocalAdminHelpers.NetLocalGroupGetMembers(ResolvedEntry entry, String& machineSid)
   at Sharphound2.Enumeration.LocalAdminHelpers.<>c__DisplayClass12_0.<GetSamAdmins>b__0()
   at System.Threading.Tasks.Task`1.InvokeFuture(Object futureAsObj)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at Sharphound2.Enumeration.EnumerationRunner.StartEnumeration()
   at Sharphound2.Sharphound.Main(String[] args)
---> (Inner Exception #0) System.AggregateException: AggregateException_ctor_DefaultMessage ---> System.ArgumentExceptio
n: SIDs with revision other than '1' are not supported.
Parameter name: binaryForm
   at System.Security.Principal.Win32.ConvertIntPtrSidToByteArraySid(IntPtr binaryForm)
   at System.Security.Principal.SecurityIdentifier..ctor(IntPtr binaryForm)
   at Sharphound2.Enumeration.LocalAdminHelpers.NetLocalGroupGetMembers(ResolvedEntry entry, String& machineSid)
   at Sharphound2.Enumeration.LocalAdminHelpers.<>c__DisplayClass12_0.<GetSamAdmins>b__0()
   at System.Threading.Tasks.Task`1.InvokeFuture(Object futureAsObj)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Sharphound2.Enumeration.LocalAdminHelpers.<GetSamAdmins>d__12.MoveNext()
   at Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass14_0.<StartRunner>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ArgumentException: SIDs with revision other than '1' are not supported.
Parameter name: binaryForm
   at System.Security.Principal.Win32.ConvertIntPtrSidToByteArraySid(IntPtr binaryForm)
   at System.Security.Principal.SecurityIdentifier..ctor(IntPtr binaryForm)
   at Sharphound2.Enumeration.LocalAdminHelpers.NetLocalGroupGetMembers(ResolvedEntry entry, String& machineSid)
   at Sharphound2.Enumeration.LocalAdminHelpers.<>c__DisplayClass12_0.<GetSamAdmins>b__0()
   at System.Threading.Tasks.Task`1.InvokeFuture(Object futureAsObj)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
<---

---> (Inner Exception #1) System.AggregateException: AggregateException_ctor_DefaultMessage ---> System.ArgumentExceptio
n: SIDs with revision other than '1' are not supported.
Parameter name: binaryForm
   at System.Security.Principal.Win32.ConvertIntPtrSidToByteArraySid(IntPtr binaryForm)
   at System.Security.Principal.SecurityIdentifier..ctor(IntPtr binaryForm)
   at Sharphound2.Enumeration.LocalAdminHelpers.NetLocalGroupGetMembers(ResolvedEntry entry, String& machineSid)
   at Sharphound2.Enumeration.LocalAdminHelpers.<>c__DisplayClass12_0.<GetSamAdmins>b__0()
   at System.Threading.Tasks.Task`1.InvokeFuture(Object futureAsObj)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Sharphound2.Enumeration.LocalAdminHelpers.<GetSamAdmins>d__12.MoveNext()
   at Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass14_0.<StartRunner>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ArgumentException: SIDs with revision other than '1' are not supported.
Parameter name: binaryForm
   at System.Security.Principal.Win32.ConvertIntPtrSidToByteArraySid(IntPtr binaryForm)
   at System.Security.Principal.SecurityIdentifier..ctor(IntPtr binaryForm)
   at Sharphound2.Enumeration.LocalAdminHelpers.NetLocalGroupGetMembers(ResolvedEntry entry, String& machineSid)
   at Sharphound2.Enumeration.LocalAdminHelpers.<>c__DisplayClass12_0.<GetSamAdmins>b__0()
   at System.Threading.Tasks.Task`1.InvokeFuture(Object futureAsObj)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
<---

---> (Inner Exception #2) System.AggregateException: AggregateException_ctor_DefaultMessage ---> System.ArgumentExceptio
n: SIDs with revision other than '1' are not supported.
Parameter name: binaryForm
   at System.Security.Principal.Win32.ConvertIntPtrSidToByteArraySid(IntPtr binaryForm)
   at System.Security.Principal.SecurityIdentifier..ctor(IntPtr binaryForm)
   at Sharphound2.Enumeration.LocalAdminHelpers.NetLocalGroupGetMembers(ResolvedEntry entry, String& machineSid)
   at Sharphound2.Enumeration.LocalAdminHelpers.<>c__DisplayClass12_0.<GetSamAdmins>b__0()
   at System.Threading.Tasks.Task`1.InvokeFuture(Object futureAsObj)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at Sharphound2.Enumeration.LocalAdminHelpers.<GetSamAdmins>d__12.MoveNext()
   at Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass14_0.<StartRunner>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ArgumentException: SIDs with revision other than '1' are not supported.
Parameter name: binaryForm
   at System.Security.Principal.Win32.ConvertIntPtrSidToByteArraySid(IntPtr binaryForm)
   at System.Security.Principal.SecurityIdentifier..ctor(IntPtr binaryForm)
   at Sharphound2.Enumeration.LocalAdminHelpers.NetLocalGroupGetMembers(ResolvedEntry entry, String& machineSid)
   at Sharphound2.Enumeration.LocalAdminHelpers.<>c__DisplayClass12_0.<GetSamAdmins>b__0()
   at System.Threading.Tasks.Task`1.InvokeFuture(Object futureAsObj)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
<---

```

**Comment by rvazarkar** [comment]
If this is still an issue, can you run with the --Debug flag?
