### ISSUE TITLE
Unhandled Exception in SharpHound.exe v1.0.0

### ISSUE THREAD

**Issue by TheRealHetfield** [BloodHoundAD/BloodHound#157]
The following exception occurred on a Windows 10 Professional device running SharpHound.exe v1.0.0. This is a very minor issue since the primary use case for the tool is for domain environments.

Unhandled Exception: System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException: Current security context is not associated with an Active Directory domain or forest.
   at System.DirectoryServices.ActiveDirectory.DirectoryContext.GetLoggedOnDomain()
   at System.DirectoryServices.ActiveDirectory.DirectoryContext.IsContextValid(DirectoryContext context, DirectoryContextType contextType)
   at System.DirectoryServices.ActiveDirectory.DirectoryContext.isDomain()
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at Sharphound2.Utils.GetDomain(String domainName)
   at Sharphound2.Utils.CreateDomainList()
   at Sharphound2.Utils..ctor(Options cli)
   at Sharphound2.Utils.CreateInstance(Options cli)
   at Sharphound2.Sharphound.Main(String[] args)

**Comment by rvazarkar** [comment]
Should be fixed in https://github.com/BloodHoundAD/SharpHound/commit/1f048d59ac1e2648f40ab545ce62df79cc6b5717
