### ISSUE TITLE
Neo4j Version that will work?

### ISSUE THREAD

**Issue by liamcs98** [BloodHoundAD/BloodHound#187]
Hi All,
About two weeks ago I was able to get Bloodhound and neo4j working perfectly in harmony. I foolishly erased the vm. In the mean time it looks like neo4j has had an update that breaks everything. Is this just me?

Steps to reproduce on Ubuntu 16 Server: 

1. sudo nano /etc/apt/sources.list
2. Add: deb http://http.kali.org/kali kali-rolling main contrib non-free
3. sudo apt-get update -y && sudo apt-get dist-upgrade -y
4. sudo apt-get install bloodhound 
5. neo4j console

Can someone let me know what a working version of neo4j is? (And maybe even how to get that one instead?)

Additional context/outputs: 

My version: `neo4j is already the newest version (3.3.4-0kali1)`

`Active database: graph.db
Directories in use:
  home:         /usr/share/neo4j
  config:       /usr/share/neo4j/conf
  logs:         /usr/share/neo4j/logs
  plugins:      /usr/share/neo4j/plugins
  import:       /usr/share/neo4j/import
  data:         /usr/share/neo4j/data
  certificates: /usr/share/neo4j/certificates
  run:          /usr/share/neo4j/run
Starting Neo4j.
WARNING: Max 1024 open files allowed, minimum of 40000 recommended. See the Neo4j manual.
2018-06-20 19:13:49.451+0000 INFO  ======== Neo4j 3.3.4 ========
2018-06-20 19:13:49.513+0000 INFO  Starting...
2018-06-20 19:13:49.567+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@4fcd19b3' was succ$
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@4fcd19b3' was successfully initiali$
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@4fcd19b3' was successfully initialized, b$
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
        ... 3 more
Caused by: java.lang.RuntimeException: java.io.IOException: Unable to create directory path [/usr/share/neo4j/logs] for Neo4j store.
        at org.neo4j.kernel.impl.factory.PlatformModule.createLogService(PlatformModule.java:301)
        at org.neo4j.kernel.impl.factory.PlatformModule.<init>(PlatformModule.java:161)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.createPlatform(GraphDatabaseFacadeFactory.java:244)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:158)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:126)
        at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
        ... 5 more
Caused by: java.io.IOException: Unable to create directory path [/usr/share/neo4j/logs] for Neo4j store.
        at org.neo4j.io.fs.DefaultFileSystemAbstraction.mkdirs(DefaultFileSystemAbstraction.java:124)
        at org.neo4j.kernel.impl.logging.StoreLogService.<init>(StoreLogService.java:164)
        at org.neo4j.kernel.impl.logging.StoreLogService.<init>(StoreLogService.java:44)
        at org.neo4j.kernel.impl.logging.StoreLogService$Builder.build(StoreLogService.java:124)
        at org.neo4j.kernel.impl.factory.PlatformModule.createLogService(PlatformModule.java:297)
        ... 12 more
2018-06-20 19:13:49.569+0000 INFO  Neo4j Server shutdown initiated by request`

**Comment by davidfauth** [comment]
@liamcs98 

The latest version of Neo4j changed the default user for Docker so it would not run as root.

The easiest fix is to change permissions on the logs directory to allow other groups to have read/write access. 

You may also need to change permissions on the data directory as well.

Knowledge base article on this will be forthcoming.
