### ISSUE TITLE
Error when running Ingestor .exe

### ISSUE THREAD

**Issue by islandspapand** [BloodHoundAD/BloodHound#289]
Command runned: sharphound.exe -c group --PrettyJson -v --OU OU=XX,OU=XX,DC=XX,DC=com -d XX.XX--SkipPing
(Domain and OU changed to XX )

If i use other command i don't get any error but it never stops Emulating objects (Let it run for over a month). this also count if i use the .ps1

nhandled Exception: System.AggregateException: AggregateException_ctor_DefaultMessage ---> System.ArgumentException: Destination array is not long enough to copy all the required data. Check array length and offset.
Parameter name: binaryForm
   at System.Security.Principal.SecurityIdentifier.CreateFromBinaryForm(Byte[] binaryForm, Int32 offset)
   at Sharphound2.Extensions.GetSid(SearchResultEntry result)
   at Sharphound2.Extensions.ResolveAdEntry(SearchResultEntry result, Boolean bypassDns)
   at Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass22_0.<StartRunner>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at Sharphound2.Enumeration.EnumerationRunner.StartEnumeration()
   at Sharphound2.Sharphound.Main(String[] args)
---> (Inner Exception #0) System.ArgumentException: Destination array is not long enough to copy all the required data. Check array length and offset.
Parameter name: binaryForm
   at System.Security.Principal.SecurityIdentifier.CreateFromBinaryForm(Byte[] binaryForm, Int32 offset)
   at Sharphound2.Extensions.GetSid(SearchResultEntry result)
   at Sharphound2.Extensions.ResolveAdEntry(SearchResultEntry result, Boolean bypassDns)
   at Sharphound2.Enumeration.EnumerationRunner.<>c__DisplayClass22_0.<StartRunner>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by rvazarkar** [comment]
Try with the 3.0 release. Hopefully this is fixed
