### ISSUE TITLE
Incompatibility with Neo4j v4.1.0

### ISSUE THREAD

**Issue by RobertDiep** [BloodHoundAD/BloodHound#343]
Hi there,

During a recent engagement I ran into some issues with BloodHound v3.0.4 and Neo4j version v4.1.0 (ran with Docker for Mac OS X).

At startup after connecting to the Neo4j database, the screen stays empty and the 'executing query' hound keeps running. In the web-console the following error shows up:

```
Uncaught TypeError: e.offset.toInt is not a function
    at Function.value (bundle.js:27)
    at new e (bundle.js:27)
    at bundle.js:27
    at Array.map (<anonymous>)
    at e.value (bundle.js:27)
    at new e (bundle.js:27)
    at Object.e.onCompleted (bundle.js:15)
    at t.value (bundle.js:15)
    at t.value [as onCompleted] (bundle.js:20)
    at e.value (bundle.js:96)
    at e._dechunker.onmessage (bundle.js:96)
    at e.value (bundle.js:96)
    at e.value [as _state] (bundle.js:96)
    at e.value (bundle.js:96)
    at e._ch.onmessage (bundle.js:96)
    at WebSocket._ws.onmessage (bundle.js:96)
```

Then, when importing data into Bloodhound through the UI the following exception happens:

```
Neo4jError: Supplied bookmark [FB:kcwQ4UnnG8EHSpiGOAEqYSre1QyQ] does not conform to pattern neo4j:bookmark:v1:tx
    at file:///private/var/folders/xx/m37hj3r914x8z242rchn_vm00000gp/T/AppTranslocation/96AE664D-7FA7-46BA-906C-33F1148BF06B/d/BloodHound.app/Contents/Resources/app/dist/bundle.js:15:11562
    at new e (file:///private/var/folders/xx/m37hj3r914x8z242rchn_vm00000gp/T/AppTranslocation/96AE664D-7FA7-46BA-906C-33F1148BF06B/d/BloodHound.app/Contents/Resources/app/dist/bundle.js:15:11642)
    at e.value (file:///private/var/folders/xx/m37hj3r914x8z242rchn_vm00000gp/T/AppTranslocation/96AE664D-7FA7-46BA-906C-33F1148BF06B/d/BloodHound.app/Contents/Resources/app/dist/bundle.js:20:43351)
    at e.value (file:///private/var/folders/xx/m37hj3r914x8z242rchn_vm00000gp/T/AppTranslocation/96AE664D-7FA7-46BA-906C-33F1148BF06B/d/BloodHound.app/Contents/Resources/app/dist/bundle.js:20:42857)
    at file:///private/var/folders/xx/m37hj3r914x8z242rchn_vm00000gp/T/AppTranslocation/96AE664D-7FA7-46BA-906C-33F1148BF06B/d/BloodHound.app/Contents/Resources/app/dist/bundle.js:116:280307
    at c (file:///private/var/folders/xx/m37hj3r914x8z242rchn_vm00000gp/T/AppTranslocation/96AE664D-7FA7-46BA-906C-33F1148BF06B/d/BloodHound.app/Contents/Resources/app/dist/bundle.js:27:248032)
    at Generator._invoke (file:///private/var/folders/xx/m37hj3r914x8z242rchn_vm00000gp/T/AppTranslocation/96AE664D-7FA7-46BA-906C-33F1148BF06B/d/BloodHound.app/Contents/Resources/app/dist/bundle.js:27:247820)
    at Generator.E.forEach.e.<computed> [as next] (file:///private/var/folders/xx/m37hj3r914x8z242rchn_vm00000gp/T/AppTranslocation/96AE664D-7FA7-46BA-906C-33F1148BF06B/d/BloodHound.app/Contents/Resources/app/dist/bundle.js:27:248455)
    at c (file:///private/var/folders/xx/m37hj3r914x8z242rchn_vm00000gp/T/AppTranslocation/96AE664D-7FA7-46BA-906C-33F1148BF06B/d/BloodHound.app/Contents/Resources/app/dist/bundle.js:27:248032)
    at O (file:///private/var/folders/xx/m37hj3r914x8z242rchn_vm00000gp/T/AppTranslocation/96AE664D-7FA7-46BA-906C-33F1148BF06B/d/BloodHound.app/Contents/Resources/app/dist/bundle.js:27:249217)
    at Generator._invoke (file:///private/var/folders/xx/m37hj3r914x8z242rchn_vm00000gp/T/AppTranslocation/96AE664D-7FA7-46BA-906C-33F1148BF06B/d/BloodHound.app/Contents/Resources/app/dist/bundle.js:27:247597)
    at Generator.E.forEach.e.<computed> [as next] (file:///private/var/folders/xx/m37hj3r914x8z242rchn_vm00000gp/T/AppTranslocation/96AE664D-7FA7-46BA-906C-33F1148BF06B/d/BloodHound.app/Contents/Resources/app/dist/bundle.js:27:248455)
    at gv (file:///private/var/folders/xx/m37hj3r914x8z242rchn_vm00000gp/T/AppTranslocation/96AE664D-7FA7-46BA-906C-33F1148BF06B/d/BloodHound.app/Contents/Resources/app/dist/bundle.js:116:271783)
    at a (file:///private/var/folders/xx/m37hj3r914x8z242rchn_vm00000gp/T/AppTranslocation/96AE664D-7FA7-46BA-906C-33F1148BF06B/d/BloodHound.app/Contents/Resources/app/dist/bundle.js:116:271987)
bundle.js:116
```

The problems are solved when I downgrade to Neo4j version 4.0.6 or lower, which makes me suspect that something in the Neo4j API changed.

**Comment by hawaii67** [comment]
I have a simliar error after upgrading neo4j from version 3.5 to version 4.0.7. using bloodhound 3.0.5:

`Database 'graph.db' is unavailable`

**Comment by hawaii67** [comment]
Ok, solved it by myself. Graph.db seems to be history. Right?
Purged bloodhoud (and neo4j,  getting sure to delete /usr/share/neo4j), reinstalled bloodhound, re-importet the data from the sharphound files. Voila.

**Comment by rvazarkar** [comment]
I'm successfully using this on 4.1.0 so closing this issue
