### ISSUE TITLE
While using SharpHound Tool: Unhandled Exception: Error#

### ISSUE THREAD

**Issue by dhazh007** [BloodHoundAD/BloodHound#491]
at System.DirectoryServices.ActiveDirectory.Locator.GetDomainControllerInfo(String computerName, String domainName, String siteName, Int64 flags)
   at System.DirectoryServices.ActiveDirectory.DirectoryContext.isCurrentForest()
   at System.DirectoryServices.ActiveDirectory.DirectoryContext.GetServerName()
   at System.DirectoryServices.ActiveDirectory.DirectoryEntryManager.GetNewDirectoryEntry(String dn)
   at System.DirectoryServices.ActiveDirectory.DirectoryEntryManager.GetCachedDirectoryEntry(String distinguishedName)
   at System.DirectoryServices.ActiveDirectory.DirectoryEntryManager.ExpandWellKnownDN(WellKnownDN dn)
   at System.DirectoryServices.ActiveDirectory.Forest.get_Schema()
   at SharpHound3.DirectorySearch.CreateSchemaMap()
   at SharpHound3.DirectorySearch..ctor(String domainName, String domainController)
   at SharpHound3.Helpers.GetDirectorySearcher(String domain)
   at SharpHound3.SharpHound.<Main>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SharpHound3.SharpHound.<Main>(String[] args)

**Comment by rvazarkar** [comment]
Should hopefully be fixed in vnext
