### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by duncandw** [BloodHoundAD/BloodHound#528]
$Domain = "ANONYMOUSDOMAIN.NET"
$Scope = "GLOBAL"

..\SharpHound.exe --collectionmethods DCOnly --domain $Domain --outputprefix $Scope"_DCOnly" --collectallproperties --statusinterval 5000 -v 2

2022-03-10T08:16:26.5742696+00:00|INFORMATION|Status: 2469 objects finished (+495 29.74699)/s -- Using 156 MB RAM
2022-03-10T08:16:30.8987379+00:00|ERROR|error in consumer
System.NullReferenceException: Object reference not set to an instance of an object.
   at SharpHoundCommonLib.Processors.GPOLocalGroupProcessor.<ProcessGPOXmlFile>d__13.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SharpHoundCommonLib.Processors.GPOLocalGroupProcessor.<ReadGPOLocalGroups>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sharphound.Runtime.ObjectProcessors.<ProcessOUObject>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sharphound.Runtime.ObjectProcessors.<ProcessObject>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Sharphound.Runtime.LDAPConsumer.<ConsumeSearchResults>d__0.MoveNext()

**Comment by MarlieF** [comment]
I am also having this issue with 1.0.4. Anyone has any insight into how to resolve it ? it's stopping my exports.

**Comment by rvazarkar** [comment]
Can you run the debug build with the .pdb file from disk?

https://github.com/BloodHoundAD/BloodHound/tree/master/Collectors/DebugBuilds

I need a line number to figure out where this is happening

**Comment by sW33Dxplo1t** [comment]
I also ran into that issue: 

2023-03-29T08:39:04.4262239+02:00|INFORMATION|Output channel closed, waiting for output task to complete
2023-03-29T08:39:04.6919695+02:00|INFORMATION|Status: 1165 objects finished (+44 12.01031)/s -- Using 50 MB RAM
2023-03-29T08:39:04.7080000+02:00|INFORMATION|Enumeration finished in 00:01:37.5915057
2023-03-29T08:39:05.6920666+02:00|ERROR|Error running SharpHound: Object reference not set to an instance of an object.
   at Sharphound.Writers.CompStatusWriter.<FlushWriter>d__7.MoveNext() in D:\a\SharpHound\SharpHound\src\Writers\CompStatusWriter.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Sharphound.Writers.CompStatusWriter.<StartWriter>d__6.MoveNext() in D:\a\SharpHound\SharpHound\src\Writers\CompStatusWriter.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Sharphound.Runtime.CollectionTask.<StartCollection>d__10.MoveNext() in D:\a\SharpHound\SharpHound\src\Runtime\CollectionTask.cs:line 88
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Sharphound.SharpLinks.<AwaitBaseRunCompletion>d__6.MoveNext() in D:\a\SharpHound\SharpHound\src\Sharphound.cs:line 253
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Sharphound.Program.<>c__DisplayClass0_0.<<Main>b__1>d.MoveNext() in D:\a\SharpHound\SharpHound\src\Sharphound.cs:line 448
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommandLine.ParserResultExtensions.<WithParsedAsync>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Sharphound.Program.<Main>d__0.MoveNext() in D:\a\SharpHound\SharpHound\src\Sharphound.cs:line 349

Did you manged to solve this issue in the meantime?

**Comment by sW33Dxplo1t** [comment]
![image](https://user-images.githubusercontent.com/124089875/229538990-f1a33d96-3b03-40c7-905b-f8f5bfe69b7e.png)

In the FlushWriter() method, we're working with the _streamWriter object, which is currently null. I believe we just need to call the CreateFile() method first to instantiate the _streamWriter. After making this change, it appears to work without any issues.

**Comment by sW33Dxplo1t** [comment]
To ensure proper functionality, you must also set the "FileCreated" parameter to true when calling the CreateFile() method.
