### ISSUE TITLE
System.Xml.XmlException: Root element is missing

### ISSUE THREAD

**Issue by duncandw** [BloodHoundAD/BloodHound#529]
SharpHound.exe v1.0.3

$Domain = "ANONYMOUSDOMAIN.NET"
$Scope = "GLOBAL"

..\SharpHound.exe --collectionmethods DCOnly --domain $Domain --outputprefix $Scope"_DCOnly" --collectallproperties --statusinterval 5000 -v 2

2022-03-10T08:16:41.6071148+00:00|INFORMATION|Status: 2693 objects finished (+80 27.47959)/s -- Using 164 MB RAM
2022-03-10T08:16:42.9731073+00:00|ERROR|error in consumer
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XPath.XPathDocument.LoadFromReader(XmlReader reader, XmlSpace space)
   at System.Xml.XPath.XPathDocument..ctor(String uri, XmlSpace space)
   at SharpHoundCommonLib.Processors.GPOLocalGroupProcessor.<ProcessGPOXmlFile>d__13.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SharpHoundCommonLib.Processors.GPOLocalGroupProcessor.<ReadGPOLocalGroups>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sharphound.Runtime.ObjectProcessors.<ProcessOUObject>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sharphound.Runtime.ObjectProcessors.<ProcessObject>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Sharphound.Runtime.LDAPConsumer.<ConsumeSearchResults>d__0.MoveNext()

**Comment by rvazarkar** [comment]
Looks like theres a malformed XML file somewhere and we're not handling it correctly

**Comment by rvazarkar** [comment]
This should hopefully be fixed in the new ingestor.
