### ISSUE TITLE
neo4j Won't start after installing bloodhound

### ISSUE THREAD

**Issue by init5-SF** [BloodHoundAD/BloodHound#638]
**Describe the bug**
neo4j Won't start after installing bloodhound

**Platform**
Linux kali 6.0.0-kali6-amd64

**To Reproduce**
Install bloodhound using apt

**Expected behavior**
neo4j should start by running: sudo neo4j console

**Errors**
```
└─# sudo neo4j console

Directories in use:
home:         /usr/share/neo4j
config:       /usr/share/neo4j/conf
logs:         /usr/share/neo4j/logs
plugins:      /usr/share/neo4j/plugins
import:       /usr/share/neo4j/import
data:         /usr/share/neo4j/data
certificates: /usr/share/neo4j/certificates
licenses:     /usr/share/neo4j/licenses
run:          /usr/share/neo4j/run
Starting Neo4j.
2023-01-12 12:13:16.278+0000 WARN  Setting 'dbms.allow_upgrade' is removed. It no longer has any effect.
2023-01-12 12:13:16.280+0000 WARN  Use of deprecated setting 'dbms.directories.import'. It is replaced by 'server.directories.import'.
2023-01-12 12:13:16.280+0000 WARN  Use of deprecated setting 'dbms.connector.http.enabled'. It is replaced by 'server.http.enabled'.
2023-01-12 12:13:16.280+0000 WARN  Use of deprecated setting 'dbms.connector.bolt.enabled'. It is replaced by 'server.bolt.enabled'.
2023-01-12 12:13:16.281+0000 WARN  Use of deprecated setting 'dbms.connector.https.enabled'. It is replaced by 'server.https.enabled'.
2023-01-12 12:13:16.281+0000 WARN  Use of deprecated setting 'dbms.windows_service_name'. It is replaced by 'server.windows_service_name'.
2023-01-12 12:13:16.281+0000 WARN  Use of deprecated setting 'dbms.tx_log.rotation.retention_policy'. It is replaced by 'db.tx_log.rotation.retention_policy'.
2023-01-12 12:13:16.281+0000 WARN  Use of deprecated setting 'dbms.tx_state.memory_allocation'. It is replaced by 'db.tx_state.memory_allocation'.
2023-01-12 12:13:16.281+0000 WARN  Use of deprecated setting 'dbms.jvm.additional'. It is replaced by 'server.jvm.additional'.
2023-01-12 12:13:16.287+0000 INFO  Starting...
2023-01-12 12:13:16.524+0000 INFO  This instance is ServerId{7cb17b2c} (7cb17b2c-349a-4801-8e24-98b671dbbbba)
2023-01-12 12:13:16.909+0000 INFO  ======== Neo4j 5.2.0 ========
2023-01-12 12:13:23.293+0000 ERROR Failed to start Neo4j on localhost:7474.
java.lang.RuntimeException: Error starting Neo4j database server at /usr/share/neo4j/data/databases
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:255) ~[neo4j-5.2.0.jar:5.2.0]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:193) ~[neo4j-5.2.0.jar:5.2.0]
	at org.neo4j.server.CommunityBootstrapper.createNeo(CommunityBootstrapper.java:36) ~[neo4j-5.2.0.jar:5.2.0]
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:164) ~[neo4j-5.2.0.jar:5.2.0]
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:85) ~[neo4j-5.2.0.jar:5.2.0]
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:30) ~[neo4j-5.2.0.jar:5.2.0]
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.dbms.database.DefaultSystemGraphInitializer@3458eca5' was successfully initialized, but failed to start. Please see the attached cause exception "The selected target store format 'AF4.3.0' (introduced in 4.3.0) is no longer supported".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:370) ~[neo4j-common-5.2.0.jar:5.2.0]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:92) ~[neo4j-common-5.2.0.jar:5.2.0]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:246) ~[neo4j-5.2.0.jar:5.2.0]
	... 5 more
	Suppressed: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.dbms.database.DatabaseLifecycles$AllDatabaseStopper@687389a6' failed to stop. Please see the attached cause exception "System database is not (yet) available".
		at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:384) ~[neo4j-common-5.2.0.jar:5.2.0]
		at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:212) ~[neo4j-common-5.2.0.jar:5.2.0]
		at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:120) ~[neo4j-common-5.2.0.jar:5.2.0]
		at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:97) ~[neo4j-common-5.2.0.jar:5.2.0]
		at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:246) ~[neo4j-5.2.0.jar:5.2.0]
		at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:193) ~[neo4j-5.2.0.jar:5.2.0]
		at org.neo4j.server.CommunityBootstrapper.createNeo(CommunityBootstrapper.java:36) ~[neo4j-5.2.0.jar:5.2.0]
		at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:164) ~[neo4j-5.2.0.jar:5.2.0]
		at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:85) ~[neo4j-5.2.0.jar:5.2.0]
		at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:30) ~[neo4j-5.2.0.jar:5.2.0]
	Caused by: org.neo4j.graphdb.DatabaseShutdownException: This database is shutdown.
		at org.neo4j.kernel.database.SystemGraphDatabaseIdRepository.execute(SystemGraphDatabaseIdRepository.java:52) ~[neo4j-kernel-5.2.0.jar:5.2.0]
		at org.neo4j.kernel.database.SystemGraphDatabaseIdRepository.getByName(SystemGraphDatabaseIdRepository.java:40) ~[neo4j-kernel-5.2.0.jar:5.2.0]
		at org.neo4j.kernel.database.DatabaseIdRepository.getByName(DatabaseIdRepository.java:55) ~[neo4j-common-5.2.0.jar:5.2.0]
		at org.neo4j.kernel.database.MapCachingDatabaseIdRepository.lambda$getByName$0(MapCachingDatabaseIdRepository.java:53) ~[neo4j-kernel-5.2.0.jar:5.2.0]
		at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
		at org.neo4j.kernel.database.MapCachingDatabaseIdRepository.getByName(MapCachingDatabaseIdRepository.java:52) ~[neo4j-kernel-5.2.0.jar:5.2.0]
		at org.neo4j.kernel.database.DatabaseIdRepository.getByName(DatabaseIdRepository.java:55) ~[neo4j-common-5.2.0.jar:5.2.0]
		at org.neo4j.dbms.database.DatabaseRepository.getDatabaseContext(DatabaseRepository.java:54) ~[neo4j-kernel-5.2.0.jar:5.2.0]
		at org.neo4j.dbms.database.DatabaseLifecycles.defaultContext(DatabaseLifecycles.java:75) ~[neo4j-5.2.0.jar:5.2.0]
		at org.neo4j.dbms.database.DatabaseLifecycles$AllDatabaseStopper.stop(DatabaseLifecycles.java:149) ~[neo4j-5.2.0.jar:5.2.0]
		at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:380) ~[neo4j-common-5.2.0.jar:5.2.0]
		... 9 more
	Caused by: org.neo4j.dbms.api.DatabaseManagementException: System database is not (yet) available
		at org.neo4j.kernel.database.SystemGraphDatabaseIdRepository.execute(SystemGraphDatabaseIdRepository.java:52) ~[neo4j-kernel-5.2.0.jar:5.2.0]
		at org.neo4j.kernel.database.SystemGraphDatabaseIdRepository.getByName(SystemGraphDatabaseIdRepository.java:40) ~[neo4j-kernel-5.2.0.jar:5.2.0]
		at org.neo4j.kernel.database.DatabaseIdRepository.getByName(DatabaseIdRepository.java:55) ~[neo4j-common-5.2.0.jar:5.2.0]
		at org.neo4j.kernel.database.MapCachingDatabaseIdRepository.lambda$getByName$0(MapCachingDatabaseIdRepository.java:53) ~[neo4j-kernel-5.2.0.jar:5.2.0]
		at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
		at org.neo4j.kernel.database.MapCachingDatabaseIdRepository.getByName(MapCachingDatabaseIdRepository.java:52) ~[neo4j-kernel-5.2.0.jar:5.2.0]
		at org.neo4j.kernel.database.DatabaseIdRepository.getByName(DatabaseIdRepository.java:55) ~[neo4j-common-5.2.0.jar:5.2.0]
		at org.neo4j.dbms.database.DatabaseRepository.getDatabaseContext(DatabaseRepository.java:54) ~[neo4j-kernel-5.2.0.jar:5.2.0]
		at org.neo4j.dbms.database.DatabaseLifecycles.defaultContext(DatabaseLifecycles.java:75) ~[neo4j-5.2.0.jar:5.2.0]
		at org.neo4j.dbms.database.DatabaseLifecycles$AllDatabaseStopper.stop(DatabaseLifecycles.java:149) ~[neo4j-5.2.0.jar:5.2.0]
		at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:380) ~[neo4j-common-5.2.0.jar:5.2.0]
		... 9 more
Caused by: org.neo4j.graphdb.DatabaseShutdownException: This database is shutdown.
	at org.neo4j.kernel.availability.DatabaseAvailabilityGuard.assertDatabaseAvailable(DatabaseAvailabilityGuard.java:154) ~[neo4j-kernel-5.2.0.jar:5.2.0]
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginKernelTransaction(GraphDatabaseFacade.java:148) ~[neo4j-kernel-5.2.0.jar:5.2.0]
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransactionInternal(GraphDatabaseFacade.java:117) ~[neo4j-kernel-5.2.0.jar:5.2.0]
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransaction(GraphDatabaseFacade.java:92) ~[neo4j-kernel-5.2.0.jar:5.2.0]
	at org.neo4j.kernel.impl.factory.GraphDatabaseTransactions.beginTransaction(GraphDatabaseTransactions.java:113) ~[neo4j-kernel-5.2.0.jar:5.2.0]
	at org.neo4j.kernel.impl.factory.GraphDatabaseTransactions.beginTransaction(GraphDatabaseTransactions.java:107) ~[neo4j-kernel-5.2.0.jar:5.2.0]
	at org.neo4j.kernel.impl.factory.GraphDatabaseTransactions.beginTransaction(GraphDatabaseTransactions.java:102) ~[neo4j-kernel-5.2.0.jar:5.2.0]
	at org.neo4j.kernel.impl.factory.GraphDatabaseTransactions.beginTx(GraphDatabaseTransactions.java:93) ~[neo4j-kernel-5.2.0.jar:5.2.0]
	at org.neo4j.dbms.database.SystemGraphComponents.initializeSystemGraph(SystemGraphComponents.java:97) ~[neo4j-kernel-5.2.0.jar:5.2.0]
	at org.neo4j.dbms.database.DefaultSystemGraphInitializer.initializeSystemGraph(DefaultSystemGraphInitializer.java:38) ~[neo4j-5.2.0.jar:5.2.0]
	at org.neo4j.dbms.database.SystemGraphInitializer.start(SystemGraphInitializer.java:27) ~[neo4j-kernel-5.2.0.jar:5.2.0]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:353) ~[neo4j-common-5.2.0.jar:5.2.0]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:92) ~[neo4j-common-5.2.0.jar:5.2.0]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:246) ~[neo4j-5.2.0.jar:5.2.0]
	... 5 more
Caused by: org.neo4j.kernel.impl.storemigration.UnableToMigrateException: The selected target store format 'AF4.3.0' (introduced in 4.3.0) is no longer supported
	at org.neo4j.kernel.impl.storemigration.StoreMigrator.doUpgradeCheck(StoreMigrator.java:326) ~[neo4j-kernel-5.2.0.jar:5.2.0]
	at org.neo4j.kernel.impl.storemigration.StoreMigrator.upgradeIfNeeded(StoreMigrator.java:195) ~[neo4j-kernel-5.2.0.jar:5.2.0]
	at org.neo4j.kernel.database.Database.upgradeStore(Database.java:731) ~[neo4j-kernel-5.2.0.jar:5.2.0]
	at org.neo4j.kernel.database.Database.specificStart(Database.java:383) ~[neo4j-kernel-5.2.0.jar:5.2.0]
	at org.neo4j.kernel.database.AbstractDatabase.start(AbstractDatabase.java:156) ~[neo4j-kernel-5.2.0.jar:5.2.0]
	at org.neo4j.dbms.database.DatabaseLifecycles.startDatabase(DatabaseLifecycles.java:119) ~[neo4j-5.2.0.jar:5.2.0]
	at org.neo4j.dbms.database.DatabaseLifecycles$SystemDatabaseStarter.start(DatabaseLifecycles.java:142) ~[neo4j-5.2.0.jar:5.2.0]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:353) ~[neo4j-common-5.2.0.jar:5.2.0]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:92) ~[neo4j-common-5.2.0.jar:5.2.0]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:246) ~[neo4j-5.2.0.jar:5.2.0]
	... 5 more
2023-01-12 12:13:23.294+0000 INFO  Neo4j Server shutdown initiated by request
2023-01-12 12:13:23.294+0000 INFO  Stopped.
Unexpected process failure. See log for info.
Run with '--verbose' for a more detailed error message.
```

**Comment by init5-SF** [comment]
nvm, fixed it on my own.
